version: '3.8'
services:
  usuarios-db:
    image: mongo:6.0
    container_name: booking_db
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=redStak
      - MONGO_INITDB_ROOT_PASSWORD=qu1Nch1nK
      - MONGO_INITDB_DATABASE=booking_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:

networks:
  default:
    driver: bridge